version: '3.8'
services:
  app:
    image: ocaml/opam2:4.12
    working_dir: /todo-app
    volumes: 
      - ./backend:/todo-app
      - db-socket:/tmp
      - opam-data:/home/opam/.opam
    environment: 
      ENVIRONMENT: development
      DB_HOST: db
      DB_NAME: todo_app
      DB_PORT: 3306
      DB_PASSWORD: password
      DB_USER: root
      DB_SOCKET_PATH: /tmp/mysql.sock
  front:
    build:
      context: .
      dockerfile: .docker/frontend/Dockerfile
    volumes: 
      - ./frontend:/todo-app
    ports:
      - 3000:3000
    command: |
      bash -c "elm-live src/Main.elm \
        --port=3000 \
        --host=0.0.0.0 \
        --start-page=index.html \
        --proxy-host=http://app:8000/api \
        --proxy-prefix=/api \
        -- --output=assets/index.js"
  db:
    image: mysql:8.0.21
    environment: 
      MYSQL_ROOT_PASSWORD: password
    volumes: 
      - db-data:/var/lib/mysql
      - db-socket:/var/run/mysqld
volumes:
  opam-data:
  db-data:
  db-socket: